version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - student1
      - student2
      - student3
      - student4
      - student5
      - student6
      - student7
      - student8
      - student9
      - student10
      - student11
      - student12
      - student13
      - student14
      - student15
      - student16
      - student17
      - student18
      - student19
      - student20
      - student21
      - student22
      - student23
      - student24
      - student25
      - student26
      - student27
      - student28
      - student29
      - student30
      - student31
      - student32
      - student33
      - student34
      - student35
      - student36
      - student37
      - student38
      - student39
      - student40
      - student41
      - student42
      - student43
      - student44
      - student45
      - student46
      - student47
      - student48
      - student49
      - student50
      - student51
      - student52
    networks:
      - webnet

  student1:
    image: student-linux-env
    container_name: student1
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/1:/home/student/1
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student2:
    image: student-linux-env
    container_name: student2
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/2:/home/student/2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student3:
    image: student-linux-env
    container_name: student3
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/3:/home/student/3
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student4:
    image: student-linux-env
    container_name: student4
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/4:/home/student/4
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student5:
    image: student-linux-env
    container_name: student5
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/5:/home/student/5
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student6:
    image: student-linux-env
    container_name: student6
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/6:/home/student/6
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student7:
    image: student-linux-env
    container_name: student7
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/7:/home/student/7
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student8:
    image: student-linux-env
    container_name: student8
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/8:/home/student/8
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student9:
    image: student-linux-env
    container_name: student9
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/9:/home/student/9
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student10:
    image: student-linux-env
    container_name: student10
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/10:/home/student/10
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student11:
    image: student-linux-env
    container_name: student11
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/11:/home/student/11
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student12:
    image: student-linux-env
    container_name: student12
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/12:/home/student/12
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student13:
    image: student-linux-env
    container_name: student13
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/13:/home/student/13
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student14:
    image: student-linux-env
    container_name: student14
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/14:/home/student/14
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student15:
    image: student-linux-env
    container_name: student15
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/15:/home/student/15
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student16:
    image: student-linux-env
    container_name: student16
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/16:/home/student/16
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student17:
    image: student-linux-env
    container_name: student17
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/17:/home/student/17
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student18:
    image: student-linux-env
    container_name: student18
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/18:/home/student/18
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student19:
    image: student-linux-env
    container_name: student19
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/19:/home/student/19
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student20:
    image: student-linux-env
    container_name: student20
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/20:/home/student/20
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student21:
    image: student-linux-env
    container_name: student21
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/21:/home/student/21
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student22:
    image: student-linux-env
    container_name: student22
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/22:/home/student/22
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student23:
    image: student-linux-env
    container_name: student23
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/23:/home/student/23
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student24:
    image: student-linux-env
    container_name: student24
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/24:/home/student/24
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student25:
    image: student-linux-env
    container_name: student25
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/25:/home/student/25
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student26:
    image: student-linux-env
    container_name: student26
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/26:/home/student/26
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student27:
    image: student-linux-env
    container_name: student27
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/27:/home/student/27
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student28:
    image: student-linux-env
    container_name: student28
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/28:/home/student/28
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student29:
    image: student-linux-env
    container_name: student29
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/29:/home/student/29
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student30:
    image: student-linux-env
    container_name: student30
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/30:/home/student/30
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student31:
    image: student-linux-env
    container_name: student31
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/31:/home/student/31
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student32:
    image: student-linux-env
    container_name: student32
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/32:/home/student/32
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student33:
    image: student-linux-env
    container_name: student33
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/33:/home/student/33
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student34:
    image: student-linux-env
    container_name: student34
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/34:/home/student/34
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student35:
    image: student-linux-env
    container_name: student35
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/35:/home/student/35
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student36:
    image: student-linux-env
    container_name: student36
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/36:/home/student/36
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student37:
    image: student-linux-env
    container_name: student37
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/37:/home/student/37
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student38:
    image: student-linux-env
    container_name: student38
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/38:/home/student/38
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student39:
    image: student-linux-env
    container_name: student39
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/39:/home/student/39
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student40:
    image: student-linux-env
    container_name: student40
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/40:/home/student/40
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student41:
    image: student-linux-env
    container_name: student41
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/41:/home/student/41
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student42:
    image: student-linux-env
    container_name: student42
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/42:/home/student/42
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student43:
    image: student-linux-env
    container_name: student43
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/43:/home/student/43
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student44:
    image: student-linux-env
    container_name: student44
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/44:/home/student/44
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student45:
    image: student-linux-env
    container_name: student45
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/45:/home/student/45
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student46:
    image: student-linux-env
    container_name: student46
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/46:/home/student/46
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student47:
    image: student-linux-env
    container_name: student47
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/47:/home/student/47
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student48:
    image: student-linux-env
    container_name: student48
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/48:/home/student/48
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student49:
    image: student-linux-env
    container_name: student49
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/49:/home/student/49
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student50:
    image: student-linux-env
    container_name: student50
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/50:/home/student/50
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student51:
    image: student-linux-env
    container_name: student51
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/51:/home/student/51
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student52:
    image: student-linux-env
    container_name: student52
    networks:
      - webnet
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/52:/home/student/52
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

networks:
  webnet:
