version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host
    depends_on:
      - student0
      - student1
      - student2

  student0-mysql:
    image: mysql:5.7
    container_name: student0-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=student_password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=student
      - MYSQL_PASSWORD=student_password
    ports:
      - "31000:3306"
    volumes:
      - ./volume/mysql/0:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student0:
    image: student-linux-env
    container_name: student0
    ports:
      - "30000:7681"
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/0:/home/student/0
    depends_on:
      - student0-mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student1-mysql:
    image: mysql:5.7
    container_name: student1-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=student_password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=student
      - MYSQL_PASSWORD=student_password
    ports:
      - "31001:3306"
    volumes:
      - ./volume/mysql/1:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student1:
    image: student-linux-env
    container_name: student1
    ports:
      - "30001:7681"
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/1:/home/student/1
    depends_on:
      - student1-mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student2-mysql:
    image: mysql:5.7
    container_name: student2-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=student_password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=student
      - MYSQL_PASSWORD=student_password
    ports:
      - "31002:3306"
    volumes:
      - ./volume/mysql/2:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  student2:
    image: student-linux-env
    container_name: student2
    ports:
      - "30002:7681"
    volumes:
      - ./volume/share:/home/student/share:ro
      - ./volume/student/2:/home/student/2
    depends_on:
      - student2-mysql
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

networks:
  webnet:
